### PR TITLE
use language: julia on travis

### PR DESCRIPTION
**Pull request by tkelman**
the ppa doesn't allow easy testing against julia 0.3 any more

### CODE REVIEW

**Comment by tkelman** [comment]
I'm not sure how to fix `ERROR: load not defined`, presumably Images.jl changed API between its most recent Julia-0.3-compatible version and the latest 0.4-compatible version.

If you want to drop support for Julia 0.3, you should change the minimum Julia version in your `REQUIRE` file and tag the package with a new minor version via `Pkg.tag("FaceDatasets", :minor)`.

**Comment by dfdx** [comment]
I think dropping support for Julia 0.4 is a way to go, I'll do it later today. Thanks.

**Comment by tkelman** [comment]
May still be a good idea to switch to `language: julia`, but given df24f58ff911128a1690c150525d9fbdd00eb064, Compat.jl is likely not necessary and the `0.3` line can be removed.

**Comment by dfdx** [comment]
I see it fails on Travis even with `language: julia`, working on it.

**Comment by tkelman** [comment]
Looks like you need to separately add the ImageMagick package to `REQUIRE`? That was another breaking change in Images.jl. It might only be needed as a test-only dependency in `test/REQUIRE`, I'm not sure what your requirements are. Anyway it looks like you have things under control so I'll close this.

**Comment by dfdx** [comment]
The package is now fixed in master. Thanks for your help!

**Pull request closed without merging**
